version: '3.9'
services:
  db:
    image: postgres:16-alpine
    container_name: cookbook_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: cookbook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: cookbook_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./
      dockerfile: backend/Dockerfile
    container_name: cookbook_backend
    depends_on:
      - db
      - redis
    environment:
      APP_NAME: "CookBook API"
      ENV: dev
      DEBUG: "true"
      HOST: 0.0.0.0
      PORT: 8000
      SECRET_KEY: change-me-secret
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/cookbook
      REDIS_URL: redis://redis:6379/0
      TOKEN_BLACKLIST_TTL_SECONDS: 1800
      FRONTEND_URL: http://localhost:5173
      RESET_TOKEN_TTL_SECONDS: 1800
      # S3/SMTP optional
      S3_BUCKET: ""
      S3_REGION: ""
      S3_ENDPOINT: ""
      S3_ACCESS_KEY_ID: ""
      S3_SECRET_ACCESS_KEY: ""
      SMTP_HOST: ""
      SMTP_PORT: 465
      SMTP_USER: ""
      SMTP_PASSWORD: ""
      SMTP_FROM: ""
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./
      dockerfile: frontend/Dockerfile
    container_name: cookbook_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data:

