"""init

Revision ID: 0eac19fc2d8d
Revises:
Create Date: 2025-08-17 11:59:04.287921

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "0eac19fc2d8d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
